package me.git9527.util;

public enum EnvKeys {

    SESSION_ENDPOINT,
    KEYPAIR_FOLDER,
    GODADDY_KEY,
    GODADDY_SECRET,
    GODADDY_SLEEP,
    DOMAIN_LIST,
    OSS_ENDPOINT,
    OSS_ACCESS_KEY,
    OSS_ACCESS_SECRET,
    OSS_BUCKET;
}
