package me.git9527.util;

public enum EnvKeys {

    SESSION_ENDPOINT,
    KEYPAIR_FOLDER,
    DOMAIN_LIST,
    EXPIRE_BEFORE_DAY,
    OSS_ENDPOINT,
    OSS_ACCESS_KEY,
    OSS_ACCESS_SECRET,
    OSS_BUCKET,
    OSS_PREFIX,
    DNS_PROVIDER,
    DNS_ALI_ACCESS_KEY,
    DNS_ALI_ACCESS_SECRET,
    DNS_SLEEP,
    DNS_LOOP_RETRY,
    DNS_GODADDY_KEY,
    DNS_GODADDY_SECRET;
}
